Source/Frontend/Models/AddNewGame.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Frontend.Models
{
    public class AddNewGame
    {
        [Required(ErrorMessage = "Required field")]
        [MinLength(3, ErrorMessage = "Minimum 3 characters"), MaxLength(30)]
        [RegularExpression("^[a-zA-Z]+$", ErrorMessage = "Only english alphabetical characters")]
        public string SessionName { get; set; }

        [Required(ErrorMessage = "Required field")]
        [MinLength(3, ErrorMessage = "Minimum 3 characters"), MaxLength(30)]
        [RegularExpression("^[a-zA-Z]+$", ErrorMessage = "Only english alphabetical characters")]
        public string PlayerOne { get; set; }

        [Required(ErrorMessage = "Required field")]
        [MinLength(3, ErrorMessage = "Minimum 3 characters"), MaxLength(30)]
        [RegularExpression("^[a-zA-Z]+$", ErrorMessage = "Only english alphabetical characters")]
        public string PlayerTwo { get; set; }

        [MaxLength(30)]
        [RegularExpression("^[a-zA-Z]+$", ErrorMessage = "Only english alphabetical characters")]
        public string PlayerThree { get; set; }

        [MaxLength(30)]
        [RegularExpression("^[a-zA-Z]+$", ErrorMessage = "Only english alphabetical characters")]
        public string PlayerFour { get; set; }
    }
}

Source/Frontend/Models/Enums.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Frontend.Models
{
    public enum PawnColor
    {
        Red = 1,
        Green = 2,
        Blue = 3,
        Yellow = 4
    }
}

Source/Frontend/Models/GameSessionResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Frontend.Models
{
    public class GameSessionResponse
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public List<Player> Players { get; set; }
        public bool ActiveGame { get; set; }
        public int CurrentPlayer { get; set; }
        public int LatestRoll { get; set; }
        public bool HasRolled { get; set; }
    }
}

Source/Frontend/Models/Pawn.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Frontend.Models
{
    public class Pawn
    {
        public int ID { get; set; }
        public int Position { get; set; }
        public bool AtFinishLine { get; set; }
        public bool IsFinished { get; set; }
        public bool IsInNest { get; set; }
        public PawnColor Color { get; set; }
        public int PlayerId { get; set; }
    }
}

Source/Frontend/Models/Player.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Frontend.Models
{
    public class Player
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Pawn> Pawns { get; set; }
        public Guid GameSessionId { get; set; }
    }
}

Source/Frontend/Pages/CreateGame.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Frontend.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestSharp;

namespace Frontend.Pages
{
    public class CreateGameModel : PageModel
    {
        [BindProperty] 
        public AddNewGame NewGame { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid == false)
            {
                return Page();
            }

            var client = new RestClient("https://localhost:44303/api/Ludo/NewGame");
            client.Timeout = -1;
            var request = new RestRequest(Method.POST);
            request.AddJsonBody(NewGame);
            IRestResponse response = client.Execute(request);
            var sessionIdResponse = response.Content;

            var sessionId = sessionIdResponse.Substring(1, 36);
            var url = $"/ludo/{sessionId}";
            return Redirect(url);
        }
    }
}

Source/Frontend/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Frontend.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Source/Frontend/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Frontend.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Source/Frontend/Pages/JoinGame.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Frontend.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestSharp;

namespace Frontend.Pages
{
    public class JoinGameModel : PageModel
    {
        public GameSessionResponse GameSession;
        [BindProperty(SupportsGet = true)]
        public Guid SessionId { get; set; }

        public IActionResult OnPostJoin()
        {
            var client = new RestClient("https://localhost:44303/api");
            client.Timeout = -1;
            var request = new RestRequest($"/Ludo/{SessionId}", DataFormat.Json);
            var response = client.Get<GameSessionResponse>(request);

            var url = $"/Ludo/{response.Data.Id}";

            return Redirect(url);


        }
    }
}

Source/Frontend/Pages/Ludo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Frontend.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using RestSharp;

namespace Frontend.Pages
{
    public class LudoModel : PageModel
    {
        private readonly ILogger<LudoModel> _logger;
        public GameSessionResponse GameSession;

        public LudoModel(ILogger<LudoModel> logger)
        {
            _logger = logger;
        }

        public void OnGet(Guid id)
        {
            var client = new RestClient("https://localhost:44303/api");
            client.Timeout = -1;
            var request = new RestRequest($"/Ludo/{id}", DataFormat.Json);

            var response = client.Get<GameSessionResponse>(request);

            GameSession = response.Data;
        }

        public void RollDice()
        {

        }
    }
}

Source/Frontend/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Frontend.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Source/Frontend/Pages/CreateGame.cshtml
@page
@model CreateGameModel
@{
    ViewData["Title"] = "Create New Game";
}


<div class="container-fluid margtop">
    <h1 class="text-center margb">Create New Game</h1>
    <div class="row align-items-center">
        <div class="col-12">
            <form asp-for="AddNewGame" method="post" id="group">
                <div class="control-group from-group">
                    <div class="controls">
                        <label asp-for="NewGame.SessionName">Session name:</label>
                        <input asp-for="NewGame.SessionName" class="form-control" />
                        <span asp-validation-for="NewGame.SessionName" class="error-message-color"></span>

                        <p class="help-block"></p>
                    </div>
                </div>
                <div class="controls">
                    <input type="radio" name="players" value="2 Players" id="player2" checked="checked" /> 2 Players
                    <input type="radio" name="players" value="3 Players" id="player3" /> 3 Players
                    <input type="radio" name="players" value="4 Players" id="player4" /> 4 Players
                    <p class="help-block"></p>
                </div>
                <div class="control-group from-group">
                    <div class="controls">
                        <label asp-for="NewGame.PlayerOne">Player 1 name:</label>
                        <input asp-for="NewGame.PlayerOne" class="form-control" />
                        <span asp-validation-for="NewGame.PlayerOne" class="error-message-color"></span>
                        <p class="help-block"></p>
                    </div>
                </div>
                <div class="control-group from-group">
                    <div class="controls">
                        <label asp-for="NewGame.PlayerTwo">Player 2 name:</label>
                        <input asp-for="NewGame.PlayerTwo" class="form-control" />
                        <span asp-validation-for="NewGame.PlayerTwo" class="error-message-color"></span>

                        <p class="help-block"></p>
                    </div>
                </div>
                <div class="control-group from-group pl3">
                    <div class="controls">
                        <label asp-for="NewGame.PlayerThree" id="p3">Player 3 name:</label>
                        <input asp-for="NewGame.PlayerThree" class="form-control" />
                        <span asp-validation-for="NewGame.PlayerThree" class="error-message-color"></span>

                        <p class="help-block"></p>
                    </div>
                </div>
                <div class="control-group from-group pl4">
                    <div class="controls">
                        <label asp-for="NewGame.PlayerFour" id="p4">Player 4 name:</label>
                        <input asp-for="NewGame.PlayerFour" class="form-control" />
                        <span asp-validation-for="NewGame.PlayerFour" class="error-message-color"></span>

                        <p class="help-block"></p>
                    </div>
                </div>
                <button type="submit" class="btn btn-success" id="sendMessageButton">Create!</button>
                <button type="button" class="btn btn-outline-warning">Clear form</button>
            </form>
        </div>
    </div>
</div>

Source/Frontend/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To Ludo Game</h1>
    <img class="ludo-image" src="img/gameplay.png"/>

    
</div>


<div class="container">
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Create new game</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">Invite up to 3 friends</h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Enter a gamesession name</li>
                    <li>Enter names for up to 4 players</li>
                    <li>Create the game</li>
                    <li>Send the gamesession Id to your friends</li>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-primary">Create game</button>
            </div>
        </div>
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Join Game session</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">Play with your friends</h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Go to Join Game</li>
                    <li>Enter a valid gamesession Id</li>
                    <li>Join the game</li>
                    <li>Have fun!</li>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-primary">Join game</button>
            </div>
        </div>
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Developers</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">Who created the game?</h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Patric</li>
                    <li>Jonas</li>
                    <li>Sebastian</li>
                    <li>Students at Teknikhögskolan</li>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-primary">Contact us</button>
            </div>
        </div>
    </div>
</div>

Source/Frontend/Pages/JoinGame.cshtml
@page
@model Frontend.Pages.JoinGameModel
@{
}
<br />
<br />
<h1>Join game</h1>
<br/>
<p>
    Please enter the gamesession id for the gamesession you want to join.
</p>
<br/><br/>
<form asp-page-handler="join" method="post">
    <div class="input-group">
        <input type="text" asp-for="SessionId" class="form-control rounded" placeholder="Enter gamesession Id"/>
        <button type="submit" class="btn btn-outline-primary">Join game</button>
    </div>
</form>

Source/Frontend/Pages/Ludo.cshtml
@page "/Ludo/{id}"
@using Frontend.Models
@model Frontend.Pages.LudoModel
@{
}


<body onload="connect()"></body>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h1 class="text-center margtop">@Model.GameSession.Name</h1>

        </div>
    </div>
    <div class="row">
        <div class="col-8">
            <table class="table">
                <tr>
                    <td colspan="5" rowspan="5" class="greenNest"></td>
                    <td class="square-1"> </td>
                    <td class="square-2"></td>
                    <td class="square-3"></td>
                    <td colspan="5" rowspan="5" class="yellowNest"></td>
                </tr>
                <tr>
                    <td class="square-44"></td>
                    <td class="square_yellow0"></td>
                    <td class="square-4"></td> @*Gul ingång till mållinje*@
                </tr>
                <tr>
                    <td class="square-43"></td>
                    <td class="square_yellow1"></td>
                    <td class="square-5"></td>
                </tr>
                <tr>
                    <td class="square-42"></td>
                    <td class="square_yellow2"></td>
                    <td class="square-6"></td>
                </tr>
                <tr>
                    <td class="square-41"></td>
                    <td class="square_yellow3"></td>
                    <td class="square-7"></td>
                </tr>
                <tr>
                    <td class="square-36"></td>
                    <td class="square-37"></td> @*Grön ingång till mållinje*@
                    <td class="square-38"></td>
                    <td class="square-39"></td>
                    <td class="square-40"></td>
                    <td colspan="3" rowspan="3" class="goal"></td>
                    <td class="square-8"></td>
                    <td class="square-9"></td>
                    <td class="square-10"></td>
                    <td class="square-11"></td>
                    <td class="square-12"></td>
                </tr>
                <tr>
                    <td class="square-35"></td>
                    <td class="square_green0"></td> @*Blå ingång till mållinje*@
                    <td class="square_green1"></td>
                    <td class="square_green2"></td>
                    <td class="square_green3"></td>
                    <td class="square_blue3"></td>
                    <td class="square_blue2"></td>
                    <td class="square_blue1"></td>
                    <td class="square_blue0"></td>
                    <td class="square-13"></td>
                </tr>
                <tr>
                    <td class="square-34"></td>
                    <td class="square-33"></td>
                    <td class="square-32"></td>
                    <td class="square-31"></td>
                    <td class="square-30"></td>
                    <td class="square-18"></td>
                    <td class="square-17"></td>
                    <td class="square-16"></td>
                    <td class="square-15"></td>
                    <td class="square-14"></td>
                </tr>
                <tr>
                    <td colspan="5" rowspan="5" class="redNest"></td>
                    <td class="square-29"></td>
                    <td class="square_red3"></td>
                    <td class="square-19"></td>
                    <td colspan="5" rowspan="5" class="blueNest"></td>
                </tr>
                <tr>
                    <td class="square-28"></td>
                    <td class="square_red2"></td>
                    <td class="square-20"></td>
                </tr>
                <tr>
                    <td class="square-27"></td>
                    <td class="square_red1"></td>
                    <td class="square-21"></td>
                </tr>
                <tr>
                    <td class="square-26"></td> @*Röd ingång till mållinje*@
                    <td class="square_red0"></td>
                    <td class="square-22"></td>
                </tr>
                <tr>
                    <td class="square-25"></td>
                    <td class="square-24"></td>
                    <td class="square-23"></td>
                </tr>
            </table>

        </div>
        <div class="col-4">

            <h2 id="currentPlayer" class="current-player">Current player: @Model.GameSession.Players[@Model.GameSession.CurrentPlayer].Name</h2>
            <p id="diceValue" class="roll"></p>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <img id="diceVisual" src="~/img/dice-5.png" alt="Playing dice" class="dice" />
        </div>
        <div class="col-8">
            <button id="diceBtn" class="btnRoll float-right" onclick="rollDice('@Model.GameSession.Id')">🎲 Roll Dice</button>
            <br/><br/><br/>
            <button class="btnRoll float-right" id="get-session-id">Get invite link</button>
        </div>
    </div>
</div>
<div id="sessionIdModal" class="modal">
    <!-- Modal content -->
    <div class="modal-content">
        <span class="close">&times;</span>
        <p>@Model.GameSession.Id</p>
    </div>
</div>
@foreach (var player in Model.GameSession.Players)
{
    foreach (var pawn in player.Pawns)
    {
        <script type="text/javascript">
                PositionPawn('@pawn.Position', '@pawn.IsInNest', '@pawn.AtFinishLine', '@pawn.IsFinished', '@pawn.Color', '@pawn.ID', '@Model.GameSession.Id');
        </script>
    }
}

Source/Frontend/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Ludogame v2 grupp 3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/Ludo.js"></script>
    <script src="~/js/onLoad.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Ludogame</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-page="/CreateGame">New Game</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-page="/JoinGame">Join Game</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Patric - Jonas - Sebastian <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/movepawn.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>